name: Build Afraa APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Flet
        run: pip install flet==0.28.3

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Copy icon to root
        run: cp assets/icon.png icon.png

      - name: Build APK
        run: yes | flet build apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: afraa-apk
          path: build/apk/*.apk
